<?php

namespace Database\Seeders;

use App\Models\Page;
use App\Models\User;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first();

        $pages = [
            [
                'title' => 'Home',
                'slug' => 'home',
                'template' => 'default',
                'meta_description' => 'Accountant General\'s Department - Government of St. Kitts and Nevis',
                'meta_keywords' => 'accountant general, st kitts nevis, government, treasury',
                'is_published' => true,
                'show_in_menu' => true,
                'menu_order' => 1,
                'created_by' => $user->id,
            ],
            [
                'title' => 'About Us',
                'slug' => 'about',
                'template' => 'default',
                'meta_description' => 'Learn about the Accountant General\'s Department',
                'meta_keywords' => 'about, accountant general, history',
                'is_published' => true,
                'show_in_menu' => true,
                'menu_order' => 2,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Divisions',
                'slug' => 'divisions',
                'template' => 'default',
                'meta_description' => 'Our divisions and departments',
                'meta_keywords' => 'divisions, departments, structure',
                'is_published' => true,
                'show_in_menu' => true,
                'menu_order' => 3,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Team',
                'slug' => 'team',
                'template' => 'default',
                'meta_description' => 'Meet our team members',
                'meta_keywords' => 'team, staff, personnel',
                'is_published' => true,
                'show_in_menu' => true,
                'menu_order' => 4,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Services',
                'slug' => 'services',
                'template' => 'default',
                'meta_description' => 'Services provided by the department',
                'meta_keywords' => 'services, government services',
                'is_published' => true,
                'show_in_menu' => true,
                'menu_order' => 5,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Government Payroll Services',
                'slug' => 'government-payroll-services',
                'template' => 'default',
                'meta_description' => 'Information about government payroll services',
                'is_published' => true,
                'show_in_menu' => false,
                'parent_id' => null,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Pension Services',
                'slug' => 'pension-services',
                'template' => 'default',
                'meta_description' => 'Government pension services and information',
                'is_published' => true,
                'show_in_menu' => false,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Cash Collection',
                'slug' => 'cash-collection',
                'template' => 'default',
                'meta_description' => 'Cash collection services',
                'is_published' => true,
                'show_in_menu' => false,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Investment Services',
                'slug' => 'investment-services',
                'template' => 'default',
                'meta_description' => 'Government investment services',
                'is_published' => true,
                'show_in_menu' => false,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Financial Reports',
                'slug' => 'financial-reports',
                'template' => 'default',
                'meta_description' => 'Government financial reports and documents',
                'meta_keywords' => 'financial reports, budget, statements',
                'is_published' => true,
                'show_in_menu' => true,
                'menu_order' => 6,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Annual Budget',
                'slug' => 'annual-budget',
                'template' => 'default',
                'meta_description' => 'Annual budget documents',
                'is_published' => true,
                'show_in_menu' => false,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Audited Financial Statements',
                'slug' => 'audited-financial-statements',
                'template' => 'default',
                'meta_description' => 'Audited financial statements',
                'is_published' => true,
                'show_in_menu' => false,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Debt Overview',
                'slug' => 'debt-overview',
                'template' => 'default',
                'meta_description' => 'Government debt overview and reports',
                'is_published' => true,
                'show_in_menu' => false,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Domestic & External Debt Reports',
                'slug' => 'domestic-external-debt-reports',
                'template' => 'default',
                'meta_description' => 'Domestic and external debt reports',
                'is_published' => true,
                'show_in_menu' => false,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Government Guarantees',
                'slug' => 'government-guarantees',
                'template' => 'default',
                'meta_description' => 'Government guarantees information',
                'is_published' => true,
                'show_in_menu' => false,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Estimates',
                'slug' => 'estimates',
                'template' => 'default',
                'meta_description' => 'Government estimates and projections',
                'is_published' => true,
                'show_in_menu' => false,
                'created_by' => $user->id,
            ],
            [
                'title' => 'News & Updates',
                'slug' => 'news',
                'template' => 'default',
                'meta_description' => 'Latest news and updates from the Treasury',
                'meta_keywords' => 'news, updates, announcements',
                'is_published' => true,
                'show_in_menu' => true,
                'menu_order' => 7,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Treasury News',
                'slug' => 'treasury-news',
                'template' => 'default',
                'meta_description' => 'Treasury news and announcements',
                'is_published' => true,
                'show_in_menu' => false,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Public Notices',
                'slug' => 'public-notices',
                'template' => 'default',
                'meta_description' => 'Public notices and announcements',
                'is_published' => true,
                'show_in_menu' => false,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Treasury Circulars',
                'slug' => 'treasury-circulars',
                'template' => 'default',
                'meta_description' => 'Treasury circulars and directives',
                'is_published' => true,
                'show_in_menu' => false,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Downloads',
                'slug' => 'download',
                'template' => 'default',
                'meta_description' => 'Download forms and documents',
                'meta_keywords' => 'downloads, forms, documents',
                'is_published' => true,
                'show_in_menu' => true,
                'menu_order' => 8,
                'created_by' => $user->id,
            ],
            [
                'title' => 'Contact Us',
                'slug' => 'contact',
                'template' => 'default',
                'meta_description' => 'Contact the Accountant General\'s Department',
                'meta_keywords' => 'contact, location, phone, email',
                'is_published' => true,
                'show_in_menu' => true,
                'menu_order' => 9,
                'created_by' => $user->id,
            ],
        ];

        foreach ($pages as $pageData) {
            Page::create($pageData);
        }
    }
}
